# Generated by Django 4.1.1 on 2022-09-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rollNo', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('phoneNumber', models.IntegerField(max_length=10)),
            ],
        ),
    ]
