# Generated by Django 4.1.1 on 2022-09-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messReg', '0002_alter_studentdetails_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
